#[STEP 1] 단어를 집합으로 변환하여 출력하기

In [1]:
!pip install konlpy
from konlpy.tag import Okt
okt=Okt()
sentence = "서울 대전 대구 부산 광주 울산 인천 제주"
words = okt.morphs(sentence)
print(words)

     |████████████████████████████████| 19.4 MB 40.6 MB/s 
     |████████████████████████████████| 86 kB 6.4 MB/s 
     |████████████████████████████████| 448 kB 73.4 MB/s 
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
['서울', '대전', '대구', '부산', '광주', '울산', '인천', '제주']


#[STEP 2] 제시된 단어를 원핫 벡터로 변환하여 출력하기

In [2]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

encoder = LabelEncoder()                      # 모든 문자를 정수형으로 변환
encoder.fit(words)
result1 = encoder.transform(words)
print(result1)

result2 = result1.reshape(-1, 1)              # 2차원 데이터로 변환
print(result2)

one_hot = OneHotEncoder()                     # 원핫 인코딩 적용
one_hot.fit(result2)
result3 = one_hot.transform(result2)
result4 = result3.toarray()
print(result4)

[4 2 1 3 0 5 6 7]
[[4]
 [2]
 [1]
 [3]
 [0]
 [5]
 [6]
 [7]]
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


#[STEP 3] 단어별 빈도수 확인하기


In [3]:
from sklearn.feature_extraction.text import CountVectorizer
text = '''
        집합, 벡터는 텍스트 데이터에서 중요한 수학적 표현 도구입니다.
        특히 벡터는 단어의 빈도수를 표현할 수 있습니다.
        따라서 텍스트 데이터에서 벡터는 매우 중요합니다.
      '''
corpus = [text]
vector = CountVectorizer()
print(vector.fit_transform(corpus).toarray())  # 코퍼스로부터 각 단어의 빈도수를 기록
print(sorted(vector.vocabulary_.items()))      # 각 단어의 인덱스가 어떻게 부여되었는지를 보여 줌.

[[1 2 1 1 1 3 1 1 1 1 1 1 2 1 1 1]]
[('단어의', 0), ('데이터에서', 1), ('도구입니다', 2), ('따라서', 3), ('매우', 4), ('벡터는', 5), ('빈도수를', 6), ('수학적', 7), ('있습니다', 8), ('중요한', 9), ('중요합니다', 10), ('집합', 11), ('텍스트', 12), ('특히', 13), ('표현', 14), ('표현할', 15)]
