2-2 정형데이터- 리스트를 배열로 표현하기

In [ ]:
import numpy as np

내과 = [79, 60, 50, 31]
외과 = [25, 8, 6, 3]
정형외과 = [28, 28, 26, 17]
소아청소년과 = [28, 28, 25, 23]
안과 = [68, 18, 15, 14]

병원수 = np.array([내과, 외과, 정형외과, 소아청소년과, 안과])

print(병원수)

print(병원수.shape)

[[79 60 50 31]
 [25  8  6  3]
 [28 28 26 17]
 [28 28 25 23]
 [68 18 15 14]]
(5, 4)
